### ISSUE TITLE
Problem with convert_weigth

### ISSUE THREAD

**Issue by b4zz4** [bryandlee/naver-webtoon-faces#6]
`python convert_weight.py --repo ~/src/naver-webtoon-faces/stylegan2/ ~/src/naver-webtoon-data/naver_webtoon_face_data_2021-07-03.pkl `

```
Traceback (most recent call last):
  File "/home/bazza/src/naver-webtoon-faces/stylegan2/convert_weight.py", line 11, in <module>
    from model import Generator, Discriminator
  File "/home/bazza/src/naver-webtoon-faces/stylegan2/model.py", line 11, in <module>
    from .op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
ImportError: attempted relative import with no known parent package
```

Try several converters but don't work.
Would you be compatible with stylegan2?

`python convert_weight.py --repo ~/src/stylegan2/ ~/src/naver-webtoon-data/naver_webtoon_face_data_2021-07-03.pkl Violación de segmento (`core' generado)`

**Comment by bryandlee** [comment]
Hi, the script converts the official stylegan2(tensorflow) checkpoint to a rosinality's stylegan2(pytorch) checkpoint. You can find out more about it [here](https://github.com/rosinality/stylegan2-pytorch#convert-weight-from-official-checkpoints).
For the import error, try running the script inside the 'stylegan2' directory instead of the root directory.
